<?PHP
defined('CHARSET') or define('CHARSET', 'ISO-8859-1');
defined('MYSQL_ERROR') or define('MYSQL_ERROR', 'MySQL Error');
defined('LAST_QUERY') or define('LAST_QUERY', 'Last MySQL Query');
defined('ERROR_TEXT') or define('ERROR_TEXT', 'Error');
defined('LOGIN_TEXT') or define('LOGIN_TEXT', 'Login');
defined('TABLES_TEXT') or define('TABLES_TEXT', 'Tables');
defined('USERNAME_TEXT') or define('USERNAME_TEXT', 'Username');
defined('PASSWORD_TEXT') or define('PASSWORD_TEXT', 'Password');
defined('HOST_TEXT') or define('HOST_TEXT', 'Host');
defined('POWERED_BY_TEXT') or define('POWERED_BY_TEXT', 'Powered by');
defined('SELECT_A_DATABASE_TEXT') or define('SELECT_A_DATABASE_TEXT', 'Select a database');
defined('RUN_A_QUERY_TEXT') or define('RUN_A_QUERY_TEXT', 'Run a Query');
defined('EXPORT_DATABASE_TEXT') or define('EXPORT_DATABASE_TEXT', 'Export Database');
defined('LOGOUT_TEXT') or define('LOGOUT_TEXT', 'Logout');
defined('STRUCTURE_LINK') or define('STRUCTURE_LINK', 'Structure');
defined('BROWSE_LINK') or define('BROWSE_LINK', 'Browse');
defined('INDEX_LINK') or define('INDEX_LINK', 'Indexes');
defined('CHANGE_LINK') or define('CHANGE_LINK', 'Change');
defined('INSERT_LINK') or define('INSERT_LINK', 'Insert');
defined('WELCOME_TO_MQA_TEXT') or define('WELCOME_TO_MQA_TEXT', 'Welcome to MySQL Quick Admin!');
defined('PLEASE_SELECT_DB_CON_TEXT') or define('PLEASE_SELECT_DB_CON_TEXT', 'Please select a database to the left in order to continue.');
defined('ADDING_FIELDS_TEXT') or define('ADDING_FIELDS_TEXT', 'Adding fields to');
defined('FIELD_NAME_TEXT') or define('FIELD_NAME_TEXT', 'Field Name');
defined('TYPE_TEXT') or define('TYPE_TEXT', 'Type');
defined('VALUE_TEXT') or define('VALUE_TEXT', 'Value');
defined('NULL_TEXT') or define('NULL_TEXT', 'Null');
defined('DEFAULT_TEXT') or define('DEFAULT_TEXT', 'Default');
defined('EXTRA_TEXT') or define('EXTRA_TEXT', 'Extra');
defined('PRIMARY_TEXT') or define('PRIMARY_TEXT', 'Primary');
defined('OTHER_TEXT') or define('OTHER_TEXT', 'Other');
defined('FT_TEXT') or define('FT_TEXT', 'FT');
defined('ADD_TEXT') or define('ADD_TEXT', 'Add');
defined('ADDING_TABLE_TEXT') or define('ADDING_TABLE_TEXT', 'Adding the table');
defined('COMMENT_TEXT') or define('COMMENT_TEXT', 'Comment');
defined('STORAGE_TEXT') or define('STORAGE_TEXT', 'Storage');
defined('ADD_ROWS_TEXT') or define('ADD_ROWS_TEXT', 'Add more rows');
defined('SAVE_TEXT') or define('SAVE_TEXT', 'Save');
defined('NUM_FIELDS_ADD_TEXT') or define('NUM_FIELDS_ADD_TEXT', 'Number of fields to add');
defined('OK_TEXT') or define('OK_TEXT', 'OK');
defined('EXPORT_TABLES_TEXT') or define('EXPORT_TABLES_TEXT', 'Export tables in database');
defined('NAME_TEXT') or define('NAME_TEXT', 'Name');
defined('RECORDS_TEXT') or define('RECORDS_TEXT', 'Records');
defined('SIZE_TEXT') or define('SIZE_TEXT', 'Size');
defined('OVERHEAD_TEXT') or define('OVERHEAD_TEXT', 'Overhead');
defined('SELECT_UNSELECT_TEXT') or define('SELECT_UNSELECT_TEXT', 'Select/Unselect All');
defined('INCLUDE_ROWS_TEXT') or define('INCLUDE_ROWS_TEXT', 'Include rows');
defined('INCLUDE_COMMENTS_TEXT') or define('INCLUDE_COMMENTS_TEXT', 'Include comments');
defined('EXPORT_TO_TEXT') or define('EXPORT_TO_TEXT', 'Export to');
defined('YES_TEXT') or define('YES_TEXT', 'Yes');
defined('NO_TEXT') or define('NO_TEXT', 'No');
defined('TEXTAREA_TEXT') or define('TEXTAREA_TEXT', 'Textarea');
defined('FILE_TEXT') or define('FILE_TEXT', 'File');
defined('EXPORT_BT_TEXT') or define('EXPORT_BT_TEXT', 'Export');
defined('SHOW_TEXT') or define('SHOW_TEXT', 'Show');
defined('ROWS_START_ROW_TEXT') or define('ROWS_START_ROW_TEXT', 'rows starting with row');
defined('PAGES_TEXT') or define('PAGES_TEXT', 'Pages');
defined('BROWSING_TABLE_TEXT') or define('BROWSING_TABLE_TEXT', 'Browsing table');
defined('TOTAL_RECORDS_TEXT') or define('TOTAL_RECORDS_TEXT', 'Total records');
defined('VIEW_ROW_TEXT') or define('VIEW_ROW_TEXT', 'View Row');
defined('EDIT_ROW_TEXT') or define('EDIT_ROW_TEXT', 'Edit Row');
defined('DELETE_ROW_TEXT') or define('DELETE_ROW_TEXT', 'Delete Row');
defined('NO_ROWS_ERROR_TEXT') or define('NO_ROWS_ERROR_TEXT', 'There are no rows in this table.');
defined('WITH_SELECTED_TEXT') or define('WITH_SELECTED_TEXT', 'With selected');
defined('VIEW_TEXT') or define('VIEW_TEXT', 'View');
defined('EDIT_TEXT') or define('EDIT_TEXT', 'Edit');
defined('DELETE_TEXT') or define('DELETE_TEXT', 'Delete');
defined('CHANGING_STRUCTURE_TEXT') or define('CHANGING_STRUCTURE_TEXT', 'Changing table structure for');
defined('TABLES_IN_TEXT') or define('TABLES_IN_TEXT', 'Tables in');
defined('INSERT_ROW_TEXT') or define('INSERT_ROW_TEXT', 'Insert Row');
defined('EMPTY_TABLE_TEXT') or define('EMPTY_TABLE_TEXT', 'Empty Table');
defined('OPTIMIZE_TABLE_TEXT') or define('OPTIMIZE_TABLE_TEXT', 'Optimize Table');
defined('DROP_TABLE_TEXT') or define('DROP_TABLE_TEXT', 'Drop Table');
defined('EMPTY_TEXT') or define('EMPTY_TEXT', 'Empty');
defined('DROP_TEXT') or define('DROP_TEXT', 'Drop');
defined('OPTIMIZE_TEXT') or define('OPTIMIZE_TEXT', 'Optimize');
defined('CREATE_NEW_TABLE_TEXT') or define('CREATE_NEW_TABLE_TEXT', 'Create a new table');
defined('NUM_FIELDS_TEXT') or define('NUM_FIELDS_TEXT', 'Number of fields');
defined('OVERHEAD_WARNING_TEXT_1') or define('OVERHEAD_WARNING_TEXT_1', 'Your table has built up a total of');
defined('OVERHEAD_WARNING_TEXT_2') or define('OVERHEAD_WARNING_TEXT_2', 'of overhead on');
defined('OVERHEAD_WARNING_TEXT_3') or define('OVERHEAD_WARNING_TEXT_3', 'tables');
defined('TABLE_NEEDS_OPTIMIZE_TEXT') or define('TABLE_NEEDS_OPTIMIZE_TEXT', 'Your tables need to be optimized!');
defined('ARE_YOU_SURE_DROP_FIELDS_TEXT') or define('ARE_YOU_SURE_DROP_FIELDS_TEXT', 'Are you sure you want to drop these fields?');
defined('CANNOT_BE_UNDONE_TEXT') or define('CANNOT_BE_UNDONE_TEXT', 'Warning: This action CAN NOT be undone.');
defined('ARE_YOU_SURE_TEXT') or define('ARE_YOU_SURE_TEXT', 'Are you sure?');
defined('ARE_YOU_SURE_DROP_INDEX_TEXT') or define('ARE_YOU_SURE_DROP_INDEX_TEXT', 'Are you sure you want to drop these indexes?');
defined('KEYNAME_TEXT') or define('KEYNAME_TEXT', 'Keyname');
defined('FIELD_TEXT') or define('FIELD_TEXT', 'Field');
defined('CARDINALITY_TEXT') or define('CARDINALITY_TEXT', 'Cardinality');
defined('ARE_YOU_SURE_DROP_ROWS_TEXT') or define('ARE_YOU_SURE_DROP_ROWS_TEXT', 'Are you sure you want to delete these rows?');
defined('OPTIMIZE_AFTER_DELETE_TEXT') or define('OPTIMIZE_AFTER_DELETE_TEXT', 'Optimize after deletion(s)?');
defined('ARE_YOU_SURE_DROP_TABLES_TEXT') or define('ARE_YOU_SURE_DROP_TABLES_TEXT', 'Are you sure you want to drop these tables?');
defined('NO_TABLES_IN_DB_TEXT') or define('NO_TABLES_IN_DB_TEXT', 'There are no tables in this database.');
defined('EDIT_ROWS_TEXT') or define('EDIT_ROWS_TEXT', 'Edit rows in');
defined('FUNCTION_TEXT') or define('FUNCTION_TEXT', 'Function');
defined('ARE_YOU_SURE_EMPTY_TEXT') or define('ARE_YOU_SURE_EMPTY_TEXT', 'Are you sure you want to empty these tables?');
defined('INDEXES_FOR_TEXT') or define('INDEXES_FOR_TEXT', 'Table indexes for');
defined('DROP_INDEX_TEXT') or define('DROP_INDEX_TEXT', 'Drop Index');
defined('NO_INDEXES_TEXT') or define('NO_INDEXES_TEXT', 'There are no indexes in this table.');
defined('ADD_INDEX_TO_TEXT') or define('ADD_INDEX_TO_TEXT', 'Add an index to');
defined('INDEX_NAME_TEXT') or define('INDEX_NAME_TEXT', 'Index name');
defined('INDEX_TYPE_TEXT') or define('INDEX_TYPE_TEXT', 'Index type');
defined('INDEX_FIELD_TEXT') or define('INDEX_FIELD_TEXT', 'Index field');
defined('CHOOSE_TEXT') or define('CHOOSE_TEXT', 'Choose');
defined('INSERT_INTO_TEXT') or define('INSERT_INTO_TEXT', 'Insert into table');
defined('STRING_FUN_TEXT') or define('STRING_FUN_TEXT', 'String Functions');
defined('DATE_TIME_FUN_TEXT') or define('DATE_TIME_FUN_TEXT', 'Date/Time Functions');
defined('INSERT_BT_TEXT') or define('INSERT_BT_TEXT', 'Insert');
defined('QUERY_WINDOW_TEXT') or define('QUERY_WINDOW_TEXT', 'Query Window');
defined('LOAD_FILE_TEXT') or define('LOAD_FILE_TEXT', 'Load from a file');
defined('LOAD_FILE_MESS_TEXT') or define('LOAD_FILE_MESS_TEXT', 'Load your MySQL query file for execution.  The file contents will be shown above.');
defined('FILE_TEXT') or define('FILE_TEXT', 'File');
defined('PREV_QUERY_TEXT') or define('PREV_QUERY_TEXT', 'Previously run queries');
defined('QUERY_TEXT') or define('QUERY_TEXT', 'Query');
defined('NO_QUERY_ERROR_TEXT') or define('NO_QUERY_ERROR_TEXT', 'No queries have been run yet.');
defined('LOAD_TEXT') or define('LOAD_TEXT', 'Load');
defined('EXECUTE_TEXT') or define('EXECUTE_TEXT', 'Execute');
defined('TB_STRUCTURE_TEXT') or define('TB_STRUCTURE_TEXT', 'Table structure for');
defined('ADD_PRIMARY_TEXT') or define('ADD_PRIMARY_TEXT', 'Add Primary');
defined('ADD_UNIQUE_TEXT') or define('ADD_UNIQUE_TEXT', 'Add Unique');
defined('ADD_INDEX_TEXT') or define('ADD_INDEX_TEXT', 'Add Index');
defined('ADD_FULLTEXT_TEXT') or define('ADD_FULLTEXT_TEXT', 'Add FullText');
defined('BROWSE_TEXT') or define('BROWSE_TEXT', 'Browse');
defined('CHANGE_HIGH_TEXT') or define('CHANGE_HIGH_TEXT', 'Change Structure');
defined('DROP_FIELD_TEXT') or define('DROP_FIELD_TEXT', 'Drop Field');
defined('CHANGE_TEXT') or define('CHANGE_TEXT', 'Change');
defined('ADD_FIELDS_TO_TEXT') or define('ADD_FIELDS_TO_TEXT', 'Add field(s) to');
defined('ADD_FIELDS_DOT_TEXT') or define('ADD_FIELDS_DOT_TEXT', 'Add field(s)');
defined('AT_END_TEXT') or define('AT_END_TEXT', 'at the end');
defined('AT_BEGINNING_TEXT') or define('AT_BEGINNING_TEXT', 'at the beginning');
defined('AFTER_TEXT') or define('AFTER_TEXT', 'after');
defined('SYSTEM_VAR_TEXT') or define('SYSTEM_VAR_TEXT', 'System Variables');
defined('VAR_NAME_TEXT') or define('VAR_NAME_TEXT', 'Variable Name');
defined('VIEW_ROWS_TABLE_TEXT') or define('VIEW_ROWS_TABLE_TEXT', 'View rows in table');
defined('EXECUTE_QUERY_TEXT') or define('EXECUTE_QUERY_TEXT', 'Execute Query');
defined('VIEW_QUERY_TEXT') or define('VIEW_QUERY_TEXT', 'View Query');
defined('RUN_QUERY_ERROR_TEXT') or define('RUN_QUERY_ERROR_TEXT', 'Please enter a query to run');
defined('CREATE_TABLE_ERROR_TEXT_1') or define('CREATE_TABLE_ERROR_TEXT_1', 'Table');
defined('CREATE_TABLE_ERROR_TEXT_2') or define('CREATE_TABLE_ERROR_TEXT_2', 'already exists');
defined('ADD_PRIMARY_ERROR_TEXT') or define('ADD_PRIMARY_ERROR_TEXT', 'Name \'PRIMARY\' reserved for PRIMARY Index');
defined('SEARCH_LINK') or define('SEARCH_LINK', 'Search');
defined('SEARCH_TABLE_TEXT') or define('SEARCH_TABLE_TEXT', 'Searching table');
defined('CLAUSE_TEXT') or define('CLAUSE_TEXT', 'Clause');
defined('SEARCH_TEXT') or define('SEARCH_TEXT', 'Search');
defined('ORDER_TEXT') or define('ORDER_TEXT', 'Order');
defined('ALL_FIELDS_TEXT') or define('ALL_FIELDS_TEXT', 'All fields');
defined('SELECTED_FIELDS_TEXT') or define('SELECTED_FIELDS_TEXT', 'Selected fields');
defined('UNEMPTY_VALS_TEXT') or define('UNEMPTY_VALS_TEXT', 'Filled values');
defined('FILTER_TEXT') or define('FILTER_TEXT', 'Filter');
defined('VIEW_QUERY_NUM_TEXT') or define('VIEW_QUERY_NUM_TEXT', 'View query number');
defined('EDIT_QUERY_TEXT') or define('EDIT_QUERY_TEXT', 'Edit Query');
defined('EDIT_QUERY_NUM_TEXT') or define('EDIT_QUERY_NUM_TEXT', 'Edit query number');
defined('SEARCH_FIELD_TEXT') or define('SEARCH_FIELD_TEXT', 'Search Field');
defined('DISTINCT_TEXT') or define('DISTINCT_TEXT', 'Distinct');
defined('VIEW_YOUR_THEMES_TEXT') or define('VIEW_YOUR_THEMES_TEXT', 'View your installed themes');
defined('VERSION_TEXT') or define('VERSION_TEXT', 'Version');
defined('AUTHOR_TEXT') or define('AUTHOR_TEXT', 'Author');
defined('MQA_VERSION_TEXT') or define('MQA_VERSION_TEXT', 'MQA Version');
defined('DESC_TEXT') or define('DESC_TEXT', 'Description');
defined('CHARSET_TEXT') or define('CHARSET_TEXT', 'Charset');
defined('VIEW_YOUR_LANGUAGES_TEXT') or define('VIEW_YOUR_LANGUAGES_TEXT', 'View your installed languages');
defined('MQA_OFFLINE_ERROR_TEXT') or define('MQA_OFFLINE_ERROR_TEXT', 'MySQL Quick Admin is offline right now.');
defined('UNABLE_GET_DATA_ERROR_TEXT') or define('UNABLE_GET_DATA_ERROR_TEXT', 'Unable to select any databases.');
defined('DROP_DB_BUTTON_TEXT') or define('DROP_DB_BUTTON_TEXT', 'Drop Database');
defined('TABLES_TEXT') or define('TABLES_TEXT', 'Tables');
defined('DATABASES_TEXT') or define('DATABASES_TEXT', 'Databases');
defined('CREATE_NEW_DB_TEXT') or define('CREATE_NEW_DB_TEXT', 'Create a new database');
defined('ARE_YOU_SURE_DROP_DATABASES_TEXT') or define('ARE_YOU_SURE_DROP_DATABASES_TEXT', 'Are you sure you want to drop these databases?');
defined('MAKE_HTML_TEXT') or define('MAKE_HTML_TEXT', 'Make HTML');
defined('MAKE_HTML_TITLE_TEXT') or define('MAKE_HTML_TITLE_TEXT', 'Making HTML template for');
defined('FIX_FIELD_TEXT') or define('FIX_FIELD_TEXT', 'Fix field name');
defined('HTML_TEMPLATE_TEXT') or define('HTML_TEMPLATE_TEXT', 'HTML Template');
defined('HTML_TABLE_TEXT') or define('HTML_TABLE_TEXT', 'Table');
defined('HTML_FORM_TEXT') or define('HTML_FORM_TEXT', 'Form');
?>