<table class="stats" cellspacing="0" cellpadding="0">
<tr>
<td class="hed" colspan="4">SCOREBOARD</td></tr>
<tr>
<td class="scorecells">5/7</td>
<td class="scorecells"><a href=" /hoplite/teamResult.jsp?tid=350&id=5764">Baseball vs. Williams (at Wesleyan)</a></td>
<td class="scorecells">W</td>
<td class="scorecells">6-3</td>
</tr>
<tr>
<td class="scorecells">5/8</td>
<td class="scorecells"><a href=" /hoplite/teamResult.jsp?tid=350&id=5765">Baseball vs. Amherst (at Trinity)</a></td>
<td class="scorecells">L</td>
<td class="scorecells">4-1</td>
</tr>
<tr>
<td class="scorecells">5/8</td>
<td class="scorecells"><a href=" /hoplite/teamResult.jsp?tid=350&id=5766">Baseball vs. Williams (at Trinity)</a></td>
<td class="scorecells">L</td>
<td class="scorecells">9-3</td>
</tr>
</table>